apiVersion: v1
kind: Service
metadata:
  labels:
    app: deploy01
    app.kubernetes.io/instance: deploy01
  name: deploy01
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 80
  selector:
    app: deploy01
  type: NodePort